FROM nginx:alpine

COPY dist/ /usr/share/nginx/html/
COPY deploy/nginx/nginx-ssl.conf /etc/nginx/conf.d/default.conf
COPY deploy/nginx/certs/ /etc/nginx/certs/

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
