project_id = "kwhttgewgsmymrzfbyyo"

[functions.parse-sms]
verify_jwt = false

[functions.ingest-sms]
verify_jwt = false

[functions.sms-inbox]
verify_jwt = false

[functions.sms-ai-parse]
verify_jwt = true

[functions.payments-apply]
verify_jwt = true

[functions.recon-exceptions]
verify_jwt = true

[functions.reports-export]
verify_jwt = true

[functions.admin-reset-mfa]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.import-statement]
verify_jwt = true

[functions.secure-import-members]
verify_jwt = true

[functions.settle-payment]
verify_jwt = true

[functions.sms-review]
verify_jwt = true

[functions.scheduled-reconciliation]
verify_jwt = false

[functions.metrics-exporter]
verify_jwt = false
