// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/approvals" | "/admin/audit" | "/admin/countries" | "/admin/countries/[id]" | "/admin/countries/new" | "/admin/feature-flags" | "/admin/groups" | "/admin/health" | "/admin/invites" | "/admin/login" | "/admin/members" | "/admin/notifications" | "/admin/ocr" | "/admin/overview" | "/admin/partners" | "/admin/partners/[orgId]" | "/admin/partners/new" | "/admin/payments" | "/admin/reconciliation" | "/admin/reports" | "/admin/saccos" | "/admin/settings" | "/admin/staff" | "/admin/telcos" | "/admin/telcos/[id]" | "/admin/telcos/new" | "/analytics" | "/countries" | "/countries/[id]" | "/dashboard" | "/device-login" | "/first-login" | "/ikimina" | "/ikimina/[id]" | "/ikimina/[id]/deposits" | "/ikimina/[id]/members" | "/ikimina/[id]/settings" | "/ikimina/[id]/statements" | "/invite/[token]" | "/join/[groupId]" | "/login" | "/member" | "/member/groups" | "/member/groups/[id]" | "/member/groups/[id]/members" | "/member/onboard" | "/member/pay" | "/member/profile" | "/member/saccos" | "/mfa" | "/offline" | "/ops" | "/partners" | "/partners/[id]" | "/privacy" | "/profile" | "/recon" | "/reports" | "/settings/sms-consent" | "/settings/sms-ingestion" | "/staff" | "/staff/allocations" | "/staff/exceptions" | "/staff/export" | "/staff/onboarding"
type AppRouteHandlerRoutes = "/api/activity/recent" | "/api/admin/audit/export" | "/api/admin/mfa/reset" | "/api/admin/payments/assign" | "/api/admin/payments/update-status" | "/api/admin/saccos/[saccoId]/branding" | "/api/admin/saccos/fix-district" | "/api/admin/staff" | "/api/admin/staff/assign-role" | "/api/admin/staff/create" | "/api/admin/staff/memberships" | "/api/admin/staff/reset-password" | "/api/admin/staff/suspend" | "/api/authx/challenge/initiate" | "/api/authx/challenge/verify" | "/api/authx/factors/list" | "/api/cache/revalidate" | "/api/chat" | "/api/device-auth/challenge" | "/api/device-auth/devices" | "/api/device-auth/enroll" | "/api/device-auth/verify" | "/api/device-auth/verify-status" | "/api/e2e/automation-health" | "/api/e2e/factors/verify" | "/api/e2e/session" | "/api/feature-flags" | "/api/groups" | "/api/groups/[id]/join-request" | "/api/groups/[id]/members" | "/api/groups/[id]/summary" | "/api/health" | "/api/healthz" | "/api/ikimina/[id]/member-ocr" | "/api/imports/sms" | "/api/imports/statement" | "/api/invite/accept" | "/api/member/groups/[id]/join-request" | "/api/member/ocr/upload" | "/api/member/onboard" | "/api/member/pay/ussd-params" | "/api/member/saccos/add" | "/api/member/saccos/search" | "/api/memberships/sync" | "/api/mfa/channels" | "/api/mfa/confirm" | "/api/mfa/diagnostics" | "/api/mfa/email" | "/api/mfa/email/request" | "/api/mfa/email/verify" | "/api/mfa/enroll" | "/api/mfa/initiate" | "/api/mfa/passkeys/[credentialId]" | "/api/mfa/passkeys/auth" | "/api/mfa/passkeys/auth/options" | "/api/mfa/passkeys/register" | "/api/mfa/passkeys/register/options" | "/api/mfa/profile" | "/api/mfa/reset/[userId]" | "/api/mfa/status" | "/api/mfa/trusted-devices/[deviceId]" | "/api/ocr/upload" | "/api/onboard" | "/api/orgs/search" | "/api/pay/ussd-params" | "/api/reconciliation/suggest" | "/api/reports/export" | "/api/reports/preview" | "/api/saccos/add" | "/api/saccos/search" | "/api/staff/change-password" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/member" | "/staff"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/approvals": {}
  "/admin/audit": {}
  "/admin/countries": {}
  "/admin/countries/[id]": { "id": string; }
  "/admin/countries/new": {}
  "/admin/feature-flags": {}
  "/admin/groups": {}
  "/admin/health": {}
  "/admin/invites": {}
  "/admin/login": {}
  "/admin/members": {}
  "/admin/notifications": {}
  "/admin/ocr": {}
  "/admin/overview": {}
  "/admin/partners": {}
  "/admin/partners/[orgId]": { "orgId": string; }
  "/admin/partners/new": {}
  "/admin/payments": {}
  "/admin/reconciliation": {}
  "/admin/reports": {}
  "/admin/saccos": {}
  "/admin/settings": {}
  "/admin/staff": {}
  "/admin/telcos": {}
  "/admin/telcos/[id]": { "id": string; }
  "/admin/telcos/new": {}
  "/analytics": {}
  "/api/activity/recent": {}
  "/api/admin/audit/export": {}
  "/api/admin/mfa/reset": {}
  "/api/admin/payments/assign": {}
  "/api/admin/payments/update-status": {}
  "/api/admin/saccos/[saccoId]/branding": { "saccoId": string; }
  "/api/admin/saccos/fix-district": {}
  "/api/admin/staff": {}
  "/api/admin/staff/assign-role": {}
  "/api/admin/staff/create": {}
  "/api/admin/staff/memberships": {}
  "/api/admin/staff/reset-password": {}
  "/api/admin/staff/suspend": {}
  "/api/authx/challenge/initiate": {}
  "/api/authx/challenge/verify": {}
  "/api/authx/factors/list": {}
  "/api/cache/revalidate": {}
  "/api/chat": {}
  "/api/device-auth/challenge": {}
  "/api/device-auth/devices": {}
  "/api/device-auth/enroll": {}
  "/api/device-auth/verify": {}
  "/api/device-auth/verify-status": {}
  "/api/e2e/automation-health": {}
  "/api/e2e/factors/verify": {}
  "/api/e2e/session": {}
  "/api/feature-flags": {}
  "/api/groups": {}
  "/api/groups/[id]/join-request": { "id": string; }
  "/api/groups/[id]/members": { "id": string; }
  "/api/groups/[id]/summary": { "id": string; }
  "/api/health": {}
  "/api/healthz": {}
  "/api/ikimina/[id]/member-ocr": { "id": string; }
  "/api/imports/sms": {}
  "/api/imports/statement": {}
  "/api/invite/accept": {}
  "/api/member/groups/[id]/join-request": { "id": string; }
  "/api/member/ocr/upload": {}
  "/api/member/onboard": {}
  "/api/member/pay/ussd-params": {}
  "/api/member/saccos/add": {}
  "/api/member/saccos/search": {}
  "/api/memberships/sync": {}
  "/api/mfa/channels": {}
  "/api/mfa/confirm": {}
  "/api/mfa/diagnostics": {}
  "/api/mfa/email": {}
  "/api/mfa/email/request": {}
  "/api/mfa/email/verify": {}
  "/api/mfa/enroll": {}
  "/api/mfa/initiate": {}
  "/api/mfa/passkeys/[credentialId]": { "credentialId": string; }
  "/api/mfa/passkeys/auth": {}
  "/api/mfa/passkeys/auth/options": {}
  "/api/mfa/passkeys/register": {}
  "/api/mfa/passkeys/register/options": {}
  "/api/mfa/profile": {}
  "/api/mfa/reset/[userId]": { "userId": string; }
  "/api/mfa/status": {}
  "/api/mfa/trusted-devices/[deviceId]": { "deviceId": string; }
  "/api/ocr/upload": {}
  "/api/onboard": {}
  "/api/orgs/search": {}
  "/api/pay/ussd-params": {}
  "/api/reconciliation/suggest": {}
  "/api/reports/export": {}
  "/api/reports/preview": {}
  "/api/saccos/add": {}
  "/api/saccos/search": {}
  "/api/staff/change-password": {}
  "/auth/callback": {}
  "/countries": {}
  "/countries/[id]": { "id": string; }
  "/dashboard": {}
  "/device-login": {}
  "/first-login": {}
  "/ikimina": {}
  "/ikimina/[id]": { "id": string; }
  "/ikimina/[id]/deposits": { "id": string; }
  "/ikimina/[id]/members": { "id": string; }
  "/ikimina/[id]/settings": { "id": string; }
  "/ikimina/[id]/statements": { "id": string; }
  "/invite/[token]": { "token": string; }
  "/join/[groupId]": { "groupId": string; }
  "/login": {}
  "/member": {}
  "/member/groups": {}
  "/member/groups/[id]": { "id": string; }
  "/member/groups/[id]/members": { "id": string; }
  "/member/onboard": {}
  "/member/pay": {}
  "/member/profile": {}
  "/member/saccos": {}
  "/mfa": {}
  "/offline": {}
  "/ops": {}
  "/partners": {}
  "/partners/[id]": { "id": string; }
  "/privacy": {}
  "/profile": {}
  "/recon": {}
  "/reports": {}
  "/settings/sms-consent": {}
  "/settings/sms-ingestion": {}
  "/staff": {}
  "/staff/allocations": {}
  "/staff/exceptions": {}
  "/staff/export": {}
  "/staff/onboarding": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/member": never
  "/staff": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
