# Cloudflare Pages configuration for Client App
# Domain: sacco.ikanisa.com

name = "ibimina-client"
compatibility_date = "2025-10-30"
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility for API routes
compatibility_flags = ["nodejs_compat"]

# Note: For Cloudflare Pages, build configuration and environment variables
# should be set in the Cloudflare dashboard under:
# Pages > [Project] > Settings > Build & deployments
# Pages > [Project] > Settings > Environment variables
