global:
  resolve_timeout: 5m

route:
  receiver: slack-notifications
  group_by: [service]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - severity="warning"
      receiver: slack-notifications
    - matchers:
        - severity="critical"
      receiver: slack-and-pagerduty

receivers:
  - name: slack-notifications
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: "#ibimina-alerts"
        send_resolved: true
        title: "{{ .CommonLabels.alertname }}: {{ .CommonAnnotations.summary }}"
        text: |
          *Severity:* {{ .CommonLabels.severity }}
          *Service:* {{ .CommonLabels.service }}
          *Description:* {{ .CommonAnnotations.description }}
          *Details:* {{ range .Alerts }}\n- {{ .Labels.instance }} {{ .Annotations.description }}{{ end }}
  - name: slack-and-pagerduty
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: "#ibimina-alerts"
        send_resolved: true
        title: "{{ .CommonLabels.alertname }}: {{ .CommonAnnotations.summary }}"
        text: |
          *Severity:* {{ .CommonLabels.severity }}
          *Service:* {{ .CommonLabels.service }}
          *Description:* {{ .CommonAnnotations.description }}
          *Details:* {{ range .Alerts }}\n- {{ .Labels.instance }} {{ .Annotations.description }}{{ end }}
    pagerduty_configs:
      - routing_key: ${PAGERDUTY_ROUTING_KEY}
        severity: critical
        description: "{{ .CommonAnnotations.summary }}"
        details:
          service: "{{ .CommonLabels.service }}"
          documentation: "https://github.com/ibimina/ibimina/tree/main/docs/operations/observability-dashboards.md"
