global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: ibimina-metrics-exporter
    static_configs:
      - targets:
          - host.docker.internal:54321
    metrics_path: /functions/v1/metrics-exporter
