// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js";
import type {
  ResolvingMetadata,
  ResolvingViewport,
} from "next/dist/lib/metadata/types/metadata-interface.js";
import type { NextRequest } from "next/server.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> }
  ) => Promise<Response | void> | Response | void;
  POST?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> }
  ) => Promise<Response | void> | Response | void;
  PUT?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> }
  ) => Promise<Response | void> | Response | void;
  PATCH?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> }
  ) => Promise<Response | void> | Response | void;
  DELETE?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> }
  ) => Promise<Response | void> | Response | void;
  HEAD?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> }
  ) => Promise<Response | void> | Response | void;
  OPTIONS?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> }
  ) => Promise<Response | void> | Response | void;
};

// Validate ../../app/(auth)/admin/login/page.tsx
{
  const handler = {} as typeof import("../../app/(auth)/admin/login/page.js");
  handler satisfies AppPageConfig<"/admin/login">;
}

// Validate ../../app/(auth)/device-login/page.tsx
{
  const handler = {} as typeof import("../../app/(auth)/device-login/page.js");
  handler satisfies AppPageConfig<"/device-login">;
}

// Validate ../../app/(auth)/first-login/page.tsx
{
  const handler = {} as typeof import("../../app/(auth)/first-login/page.js");
  handler satisfies AppPageConfig<"/first-login">;
}

// Validate ../../app/(auth)/login/page.tsx
{
  const handler = {} as typeof import("../../app/(auth)/login/page.js");
  handler satisfies AppPageConfig<"/login">;
}

// Validate ../../app/(auth)/mfa/page.tsx
{
  const handler = {} as typeof import("../../app/(auth)/mfa/page.js");
  handler satisfies AppPageConfig<"/mfa">;
}

// Validate ../../app/(main)/admin/(panel)/approvals/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/approvals/page.js");
  handler satisfies AppPageConfig<"/admin/approvals">;
}

// Validate ../../app/(main)/admin/(panel)/audit/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/audit/page.js");
  handler satisfies AppPageConfig<"/admin/audit">;
}

// Validate ../../app/(main)/admin/(panel)/feature-flags/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/feature-flags/page.js");
  handler satisfies AppPageConfig<"/admin/feature-flags">;
}

// Validate ../../app/(main)/admin/(panel)/groups/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/groups/page.js");
  handler satisfies AppPageConfig<"/admin/groups">;
}

// Validate ../../app/(main)/admin/(panel)/health/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/health/page.js");
  handler satisfies AppPageConfig<"/admin/health">;
}

// Validate ../../app/(main)/admin/(panel)/members/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/members/page.js");
  handler satisfies AppPageConfig<"/admin/members">;
}

// Validate ../../app/(main)/admin/(panel)/notifications/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/notifications/page.js");
  handler satisfies AppPageConfig<"/admin/notifications">;
}

// Validate ../../app/(main)/admin/(panel)/ocr/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/ocr/page.js");
  handler satisfies AppPageConfig<"/admin/ocr">;
}

// Validate ../../app/(main)/admin/(panel)/overview/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/overview/page.js");
  handler satisfies AppPageConfig<"/admin/overview">;
}

// Validate ../../app/(main)/admin/(panel)/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/page.js");
  handler satisfies AppPageConfig<"/admin">;
}

// Validate ../../app/(main)/admin/(panel)/payments/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/payments/page.js");
  handler satisfies AppPageConfig<"/admin/payments">;
}

// Validate ../../app/(main)/admin/(panel)/reconciliation/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/reconciliation/page.js");
  handler satisfies AppPageConfig<"/admin/reconciliation">;
}

// Validate ../../app/(main)/admin/(panel)/reports/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/reports/page.js");
  handler satisfies AppPageConfig<"/admin/reports">;
}

// Validate ../../app/(main)/admin/(panel)/saccos/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/saccos/page.js");
  handler satisfies AppPageConfig<"/admin/saccos">;
}

// Validate ../../app/(main)/admin/(panel)/settings/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/settings/page.js");
  handler satisfies AppPageConfig<"/admin/settings">;
}

// Validate ../../app/(main)/admin/(panel)/staff/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/staff/page.js");
  handler satisfies AppPageConfig<"/admin/staff">;
}

// Validate ../../app/(main)/analytics/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/analytics/page.js");
  handler satisfies AppPageConfig<"/analytics">;
}

// Validate ../../app/(main)/countries/[id]/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/countries/[id]/page.js");
  handler satisfies AppPageConfig<"/countries/[id]">;
}

// Validate ../../app/(main)/countries/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/countries/page.js");
  handler satisfies AppPageConfig<"/countries">;
}

// Validate ../../app/(main)/dashboard/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/dashboard/page.js");
  handler satisfies AppPageConfig<"/dashboard">;
}

// Validate ../../app/(main)/ikimina/[id]/deposits/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/ikimina/[id]/deposits/page.js");
  handler satisfies AppPageConfig<"/ikimina/[id]/deposits">;
}

// Validate ../../app/(main)/ikimina/[id]/members/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/ikimina/[id]/members/page.js");
  handler satisfies AppPageConfig<"/ikimina/[id]/members">;
}

// Validate ../../app/(main)/ikimina/[id]/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/ikimina/[id]/page.js");
  handler satisfies AppPageConfig<"/ikimina/[id]">;
}

// Validate ../../app/(main)/ikimina/[id]/settings/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/ikimina/[id]/settings/page.js");
  handler satisfies AppPageConfig<"/ikimina/[id]/settings">;
}

// Validate ../../app/(main)/ikimina/[id]/statements/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/ikimina/[id]/statements/page.js");
  handler satisfies AppPageConfig<"/ikimina/[id]/statements">;
}

// Validate ../../app/(main)/ikimina/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/ikimina/page.js");
  handler satisfies AppPageConfig<"/ikimina">;
}

// Validate ../../app/(main)/ops/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/ops/page.js");
  handler satisfies AppPageConfig<"/ops">;
}

// Validate ../../app/(main)/partners/[id]/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/partners/[id]/page.js");
  handler satisfies AppPageConfig<"/partners/[id]">;
}

// Validate ../../app/(main)/partners/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/partners/page.js");
  handler satisfies AppPageConfig<"/partners">;
}

// Validate ../../app/(main)/profile/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/profile/page.js");
  handler satisfies AppPageConfig<"/profile">;
}

// Validate ../../app/(main)/recon/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/recon/page.js");
  handler satisfies AppPageConfig<"/recon">;
}

// Validate ../../app/(main)/reports/page.tsx
{
  const handler = {} as typeof import("../../app/(main)/reports/page.js");
  handler satisfies AppPageConfig<"/reports">;
}

// Validate ../../app/(staff)/staff/allocations/page.tsx
{
  const handler = {} as typeof import("../../app/(staff)/staff/allocations/page.js");
  handler satisfies AppPageConfig<"/staff/allocations">;
}

// Validate ../../app/(staff)/staff/exceptions/page.tsx
{
  const handler = {} as typeof import("../../app/(staff)/staff/exceptions/page.js");
  handler satisfies AppPageConfig<"/staff/exceptions">;
}

// Validate ../../app/(staff)/staff/export/page.tsx
{
  const handler = {} as typeof import("../../app/(staff)/staff/export/page.js");
  handler satisfies AppPageConfig<"/staff/export">;
}

// Validate ../../app/(staff)/staff/onboarding/page.tsx
{
  const handler = {} as typeof import("../../app/(staff)/staff/onboarding/page.js");
  handler satisfies AppPageConfig<"/staff/onboarding">;
}

// Validate ../../app/(staff)/staff/page.tsx
{
  const handler = {} as typeof import("../../app/(staff)/staff/page.js");
  handler satisfies AppPageConfig<"/staff">;
}

{
}

{
}

{
}

// Validate ../../app/admin/invites/page.tsx
{
  const handler = {} as typeof import("../../app/admin/invites/page.js");
  handler satisfies AppPageConfig<"/admin/invites">;
}

// Validate ../../app/admin/page.tsx
{
  const handler = {} as typeof import("../../app/admin/page.js");
  handler satisfies AppPageConfig<"/admin">;
}

{
}

{
}

{
}

{
}

{
}

{
}

// Validate ../../app/invite/[token]/page.tsx
{
  const handler = {} as typeof import("../../app/invite/[token]/page.js");
  handler satisfies AppPageConfig<"/invite/[token]">;
}

// Validate ../../app/join/[groupId]/page.tsx
{
  const handler = {} as typeof import("../../app/join/[groupId]/page.js");
  handler satisfies AppPageConfig<"/join/[groupId]">;
}

// Validate ../../app/member/groups/[id]/members/page.tsx
{
  const handler = {} as typeof import("../../app/member/groups/[id]/members/page.js");
  handler satisfies AppPageConfig<"/member/groups/[id]/members">;
}

// Validate ../../app/member/groups/[id]/page.tsx
{
  const handler = {} as typeof import("../../app/member/groups/[id]/page.js");
  handler satisfies AppPageConfig<"/member/groups/[id]">;
}

// Validate ../../app/member/groups/page.tsx
{
  const handler = {} as typeof import("../../app/member/groups/page.js");
  handler satisfies AppPageConfig<"/member/groups">;
}

// Validate ../../app/member/onboard/page.tsx
{
  const handler = {} as typeof import("../../app/member/onboard/page.js");
  handler satisfies AppPageConfig<"/member/onboard">;
}

// Validate ../../app/member/page.tsx
{
  const handler = {} as typeof import("../../app/member/page.js");
  handler satisfies AppPageConfig<"/member">;
}

// Validate ../../app/member/pay/page.tsx
{
  const handler = {} as typeof import("../../app/member/pay/page.js");
  handler satisfies AppPageConfig<"/member/pay">;
}

// Validate ../../app/member/profile/page.tsx
{
  const handler = {} as typeof import("../../app/member/profile/page.js");
  handler satisfies AppPageConfig<"/member/profile">;
}

// Validate ../../app/member/saccos/page.tsx
{
  const handler = {} as typeof import("../../app/member/saccos/page.js");
  handler satisfies AppPageConfig<"/member/saccos">;
}

// Validate ../../app/offline/page.tsx
{
  const handler = {} as typeof import("../../app/offline/page.js");
  handler satisfies AppPageConfig<"/offline">;
}

// Validate ../../app/page.tsx
{
  const handler = {} as typeof import("../../app/page.js");
  handler satisfies AppPageConfig<"/">;
}

// Validate ../../app/privacy/page.tsx
{
  const handler = {} as typeof import("../../app/privacy/page.js");
  handler satisfies AppPageConfig<"/privacy">;
}

// Validate ../../app/settings/sms-consent/page.tsx
{
  const handler = {} as typeof import("../../app/settings/sms-consent/page.js");
  handler satisfies AppPageConfig<"/settings/sms-consent">;
}

// Validate ../../app/settings/sms-ingestion/page.tsx
{
  const handler = {} as typeof import("../../app/settings/sms-ingestion/page.js");
  handler satisfies AppPageConfig<"/settings/sms-ingestion">;
}

// Validate ../../app/api/activity/recent/route.ts
{
  const handler = {} as typeof import("../../app/api/activity/recent/route.js");
  handler satisfies RouteHandlerConfig<"/api/activity/recent">;
}

// Validate ../../app/api/admin/audit/export/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/audit/export/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/audit/export">;
}

// Validate ../../app/api/admin/mfa/reset/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/mfa/reset/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/mfa/reset">;
}

// Validate ../../app/api/admin/payments/assign/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/payments/assign/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/payments/assign">;
}

// Validate ../../app/api/admin/payments/update-status/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/payments/update-status/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/payments/update-status">;
}

// Validate ../../app/api/admin/saccos/[saccoId]/branding/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/saccos/[saccoId]/branding/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/saccos/[saccoId]/branding">;
}

// Validate ../../app/api/admin/saccos/fix-district/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/saccos/fix-district/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/saccos/fix-district">;
}

// Validate ../../app/api/admin/staff/assign-role/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/staff/assign-role/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/staff/assign-role">;
}

// Validate ../../app/api/admin/staff/create/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/staff/create/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/staff/create">;
}

// Validate ../../app/api/admin/staff/memberships/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/staff/memberships/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/staff/memberships">;
}

// Validate ../../app/api/admin/staff/reset-password/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/staff/reset-password/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/staff/reset-password">;
}

// Validate ../../app/api/admin/staff/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/staff/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/staff">;
}

// Validate ../../app/api/admin/staff/suspend/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/staff/suspend/route.js");
  handler satisfies RouteHandlerConfig<"/api/admin/staff/suspend">;
}

// Validate ../../app/api/authx/challenge/initiate/route.ts
{
  const handler = {} as typeof import("../../app/api/authx/challenge/initiate/route.js");
  handler satisfies RouteHandlerConfig<"/api/authx/challenge/initiate">;
}

// Validate ../../app/api/authx/challenge/verify/route.ts
{
  const handler = {} as typeof import("../../app/api/authx/challenge/verify/route.js");
  handler satisfies RouteHandlerConfig<"/api/authx/challenge/verify">;
}

// Validate ../../app/api/authx/factors/list/route.ts
{
  const handler = {} as typeof import("../../app/api/authx/factors/list/route.js");
  handler satisfies RouteHandlerConfig<"/api/authx/factors/list">;
}

// Validate ../../app/api/cache/revalidate/route.ts
{
  const handler = {} as typeof import("../../app/api/cache/revalidate/route.js");
  handler satisfies RouteHandlerConfig<"/api/cache/revalidate">;
}

// Validate ../../app/api/chat/route.ts
{
  const handler = {} as typeof import("../../app/api/chat/route.js");
  handler satisfies RouteHandlerConfig<"/api/chat">;
}

// Validate ../../app/api/device-auth/challenge/route.ts
{
  const handler = {} as typeof import("../../app/api/device-auth/challenge/route.js");
  handler satisfies RouteHandlerConfig<"/api/device-auth/challenge">;
}

// Validate ../../app/api/device-auth/devices/route.ts
{
  const handler = {} as typeof import("../../app/api/device-auth/devices/route.js");
  handler satisfies RouteHandlerConfig<"/api/device-auth/devices">;
}

// Validate ../../app/api/device-auth/enroll/route.ts
{
  const handler = {} as typeof import("../../app/api/device-auth/enroll/route.js");
  handler satisfies RouteHandlerConfig<"/api/device-auth/enroll">;
}

// Validate ../../app/api/device-auth/verify-status/route.ts
{
  const handler = {} as typeof import("../../app/api/device-auth/verify-status/route.js");
  handler satisfies RouteHandlerConfig<"/api/device-auth/verify-status">;
}

// Validate ../../app/api/device-auth/verify/route.ts
{
  const handler = {} as typeof import("../../app/api/device-auth/verify/route.js");
  handler satisfies RouteHandlerConfig<"/api/device-auth/verify">;
}

// Validate ../../app/api/e2e/automation-health/route.ts
{
  const handler = {} as typeof import("../../app/api/e2e/automation-health/route.js");
  handler satisfies RouteHandlerConfig<"/api/e2e/automation-health">;
}

// Validate ../../app/api/e2e/factors/verify/route.ts
{
  const handler = {} as typeof import("../../app/api/e2e/factors/verify/route.js");
  handler satisfies RouteHandlerConfig<"/api/e2e/factors/verify">;
}

// Validate ../../app/api/e2e/session/route.ts
{
  const handler = {} as typeof import("../../app/api/e2e/session/route.js");
  handler satisfies RouteHandlerConfig<"/api/e2e/session">;
}

// Validate ../../app/api/feature-flags/route.ts
{
  const handler = {} as typeof import("../../app/api/feature-flags/route.js");
  handler satisfies RouteHandlerConfig<"/api/feature-flags">;
}

// Validate ../../app/api/groups/[id]/join-request/route.ts
{
  const handler = {} as typeof import("../../app/api/groups/[id]/join-request/route.js");
  handler satisfies RouteHandlerConfig<"/api/groups/[id]/join-request">;
}

// Validate ../../app/api/groups/[id]/members/route.ts
{
  const handler = {} as typeof import("../../app/api/groups/[id]/members/route.js");
  handler satisfies RouteHandlerConfig<"/api/groups/[id]/members">;
}

// Validate ../../app/api/groups/[id]/summary/route.ts
{
  const handler = {} as typeof import("../../app/api/groups/[id]/summary/route.js");
  handler satisfies RouteHandlerConfig<"/api/groups/[id]/summary">;
}

// Validate ../../app/api/groups/route.ts
{
  const handler = {} as typeof import("../../app/api/groups/route.js");
  handler satisfies RouteHandlerConfig<"/api/groups">;
}

// Validate ../../app/api/health/route.ts
{
  const handler = {} as typeof import("../../app/api/health/route.js");
  handler satisfies RouteHandlerConfig<"/api/health">;
}

// Validate ../../app/api/healthz/route.ts
{
  const handler = {} as typeof import("../../app/api/healthz/route.js");
  handler satisfies RouteHandlerConfig<"/api/healthz">;
}

// Validate ../../app/api/ikimina/[id]/member-ocr/route.ts
{
  const handler = {} as typeof import("../../app/api/ikimina/[id]/member-ocr/route.js");
  handler satisfies RouteHandlerConfig<"/api/ikimina/[id]/member-ocr">;
}

// Validate ../../app/api/imports/sms/route.ts
{
  const handler = {} as typeof import("../../app/api/imports/sms/route.js");
  handler satisfies RouteHandlerConfig<"/api/imports/sms">;
}

// Validate ../../app/api/imports/statement/route.ts
{
  const handler = {} as typeof import("../../app/api/imports/statement/route.js");
  handler satisfies RouteHandlerConfig<"/api/imports/statement">;
}

// Validate ../../app/api/invite/accept/route.ts
{
  const handler = {} as typeof import("../../app/api/invite/accept/route.js");
  handler satisfies RouteHandlerConfig<"/api/invite/accept">;
}

// Validate ../../app/api/member/groups/[id]/join-request/route.ts
{
  const handler = {} as typeof import("../../app/api/member/groups/[id]/join-request/route.js");
  handler satisfies RouteHandlerConfig<"/api/member/groups/[id]/join-request">;
}

// Validate ../../app/api/member/ocr/upload/route.ts
{
  const handler = {} as typeof import("../../app/api/member/ocr/upload/route.js");
  handler satisfies RouteHandlerConfig<"/api/member/ocr/upload">;
}

// Validate ../../app/api/member/onboard/route.ts
{
  const handler = {} as typeof import("../../app/api/member/onboard/route.js");
  handler satisfies RouteHandlerConfig<"/api/member/onboard">;
}

// Validate ../../app/api/member/pay/ussd-params/route.ts
{
  const handler = {} as typeof import("../../app/api/member/pay/ussd-params/route.js");
  handler satisfies RouteHandlerConfig<"/api/member/pay/ussd-params">;
}

// Validate ../../app/api/member/saccos/add/route.ts
{
  const handler = {} as typeof import("../../app/api/member/saccos/add/route.js");
  handler satisfies RouteHandlerConfig<"/api/member/saccos/add">;
}

// Validate ../../app/api/member/saccos/search/route.ts
{
  const handler = {} as typeof import("../../app/api/member/saccos/search/route.js");
  handler satisfies RouteHandlerConfig<"/api/member/saccos/search">;
}

// Validate ../../app/api/memberships/sync/route.ts
{
  const handler = {} as typeof import("../../app/api/memberships/sync/route.js");
  handler satisfies RouteHandlerConfig<"/api/memberships/sync">;
}

// Validate ../../app/api/mfa/channels/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/channels/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/channels">;
}

// Validate ../../app/api/mfa/confirm/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/confirm/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/confirm">;
}

// Validate ../../app/api/mfa/diagnostics/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/diagnostics/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/diagnostics">;
}

// Validate ../../app/api/mfa/email/request/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/email/request/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/email/request">;
}

// Validate ../../app/api/mfa/email/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/email/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/email">;
}

// Validate ../../app/api/mfa/email/verify/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/email/verify/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/email/verify">;
}

// Validate ../../app/api/mfa/enroll/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/enroll/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/enroll">;
}

// Validate ../../app/api/mfa/initiate/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/initiate/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/initiate">;
}

// Validate ../../app/api/mfa/passkeys/[credentialId]/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/passkeys/[credentialId]/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/passkeys/[credentialId]">;
}

// Validate ../../app/api/mfa/passkeys/auth/options/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/passkeys/auth/options/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/passkeys/auth/options">;
}

// Validate ../../app/api/mfa/passkeys/auth/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/passkeys/auth/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/passkeys/auth">;
}

// Validate ../../app/api/mfa/passkeys/register/options/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/passkeys/register/options/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/passkeys/register/options">;
}

// Validate ../../app/api/mfa/passkeys/register/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/passkeys/register/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/passkeys/register">;
}

// Validate ../../app/api/mfa/profile/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/profile/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/profile">;
}

// Validate ../../app/api/mfa/reset/[userId]/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/reset/[userId]/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/reset/[userId]">;
}

// Validate ../../app/api/mfa/status/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/status/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/status">;
}

// Validate ../../app/api/mfa/trusted-devices/[deviceId]/route.ts
{
  const handler = {} as typeof import("../../app/api/mfa/trusted-devices/[deviceId]/route.js");
  handler satisfies RouteHandlerConfig<"/api/mfa/trusted-devices/[deviceId]">;
}

// Validate ../../app/api/ocr/upload/route.ts
{
  const handler = {} as typeof import("../../app/api/ocr/upload/route.js");
  handler satisfies RouteHandlerConfig<"/api/ocr/upload">;
}

// Validate ../../app/api/onboard/route.ts
{
  const handler = {} as typeof import("../../app/api/onboard/route.js");
  handler satisfies RouteHandlerConfig<"/api/onboard">;
}

// Validate ../../app/api/orgs/search/route.ts
{
  const handler = {} as typeof import("../../app/api/orgs/search/route.js");
  handler satisfies RouteHandlerConfig<"/api/orgs/search">;
}

// Validate ../../app/api/pay/ussd-params/route.ts
{
  const handler = {} as typeof import("../../app/api/pay/ussd-params/route.js");
  handler satisfies RouteHandlerConfig<"/api/pay/ussd-params">;
}

// Validate ../../app/api/reconciliation/suggest/route.ts
{
  const handler = {} as typeof import("../../app/api/reconciliation/suggest/route.js");
  handler satisfies RouteHandlerConfig<"/api/reconciliation/suggest">;
}

// Validate ../../app/api/reports/export/route.ts
{
  const handler = {} as typeof import("../../app/api/reports/export/route.js");
  handler satisfies RouteHandlerConfig<"/api/reports/export">;
}

// Validate ../../app/api/reports/preview/route.ts
{
  const handler = {} as typeof import("../../app/api/reports/preview/route.js");
  handler satisfies RouteHandlerConfig<"/api/reports/preview">;
}

// Validate ../../app/api/saccos/add/route.ts
{
  const handler = {} as typeof import("../../app/api/saccos/add/route.js");
  handler satisfies RouteHandlerConfig<"/api/saccos/add">;
}

// Validate ../../app/api/saccos/search/route.ts
{
  const handler = {} as typeof import("../../app/api/saccos/search/route.js");
  handler satisfies RouteHandlerConfig<"/api/saccos/search">;
}

// Validate ../../app/api/staff/change-password/route.ts
{
  const handler = {} as typeof import("../../app/api/staff/change-password/route.js");
  handler satisfies RouteHandlerConfig<"/api/staff/change-password">;
}

// Validate ../../app/auth/callback/route.ts
{
  const handler = {} as typeof import("../../app/auth/callback/route.js");
  handler satisfies RouteHandlerConfig<"/auth/callback">;
}

// Validate ../../app/(auth)/layout.tsx
{
  const handler = {} as typeof import("../../app/(auth)/layout.js");
  handler satisfies LayoutConfig<"/">;
}

// Validate ../../app/(main)/admin/(panel)/layout.tsx
{
  const handler = {} as typeof import("../../app/(main)/admin/(panel)/layout.js");
  handler satisfies LayoutConfig<"/admin">;
}

// Validate ../../app/(main)/layout.tsx
{
  const handler = {} as typeof import("../../app/(main)/layout.js");
  handler satisfies LayoutConfig<"/">;
}

// Validate ../../app/(staff)/staff/layout.tsx
{
  const handler = {} as typeof import("../../app/(staff)/staff/layout.js");
  handler satisfies LayoutConfig<"/staff">;
}

// Validate ../../app/admin/layout.tsx
{
  const handler = {} as typeof import("../../app/admin/layout.js");
  handler satisfies LayoutConfig<"/admin">;
}

// Validate ../../app/layout.tsx
{
  const handler = {} as typeof import("../../app/layout.js");
  handler satisfies LayoutConfig<"/">;
}

// Validate ../../app/member/layout.tsx
{
  const handler = {} as typeof import("../../app/member/layout.js");
  handler satisfies LayoutConfig<"/member">;
}
