-- Insert Deposit-Taking Microfinance Companies and additional SACCOs
INSERT INTO public.saccos (name, sector_code, district, province, email, category) VALUES
-- Deposit-Taking Microfinance Companies (1-22)
('INKINGI MICROFINANCE', 'MUHIMA', 'NYARUGENGE', 'CITY OF KIGALI', 'mfinkingi@gmail.com', 'Deposit-Taking Microfinance Company'),
('AMASEZERANO COMMUNITY BANKING PLC', 'KICUKIRO', 'KICUKIRO', 'CITY OF KIGALI', 'amasezerano@acb.rw', 'Deposit-Taking Microfinance Company'),
('VISIONFUND Rwanda PLC', 'MUHIMA', 'NYARUGENGE', 'CITY OF KIGALI', 'info@vfcrwanda.org', 'Deposit-Taking Microfinance Company'),
('SAGER GANZA MICROFINANCE PLC', 'GITEGA', 'NYARUGENGE', 'CITY OF KIGALI', 'info@sagerganza.co.rw', 'Deposit-Taking Microfinance Company'),
('COPEDU PLC', 'KICUKIRO', 'KICUKIRO', 'CITY OF KIGALI', 'info@copeduplc.rw', 'Deposit-Taking Microfinance Company'),
('DUTERIMBERE IMF PLC', 'MUHIMA', 'NYARUGENGE', 'CITY OF KIGALI', 'info@duterimbereimf.co.rw', 'Deposit-Taking Microfinance Company'),
('LETSHEGO Rwanda PLC', 'NYARUGENGE', 'NYARUGENGE', 'CITY OF KIGALI', 'info-rw@letshego.com', 'Deposit-Taking Microfinance Company'),
('GOSHEN FINANCE PLC', 'NYARUGENGE', 'NYARUGENGE', 'CITY OF KIGALI', 'info@goshenfinance.rw', 'Deposit-Taking Microfinance Company'),
('RESEAU INTERDIOCESAIN DE MICROFINANCE (RIM) PLC', 'NYARUGENGE', 'NYARUGENGE', 'CITY OF KIGALI', 'rim@rim.rw', 'Deposit-Taking Microfinance Company'),
('FINANCIAL SAFETY COMPANY LTD', 'GISENYI', 'RUBAVU', 'WESTERN PROVINCE', 'financialsafety2013@gmail.com', 'Deposit-Taking Microfinance Company'),
('ASA International Rwanda PLC', 'GISOZI', 'GASABO', 'CITY OF KIGALI', 'rwanda@asa-international.com', 'Deposit-Taking Microfinance Company'),
('CLECAM EJO HEZA PLC', 'NYAMABUYE', 'MUHANGA', 'SOUTHERN PROVINCE', 'uniclecam@gmail.com', 'Deposit-Taking Microfinance Company'),
('UMUTANGUHA FINANCE COMPANY PLC', 'NYAMIRAMBO', 'NYARUGENGE', 'CITY OF KIGALI', 'info@ufinance.co.rw', 'Deposit-Taking Microfinance Company'),
('TRUST CAPITAL KIRA MICROFINANCE PLC', 'GITEGA', 'NYARUGENGE', 'CITY OF KIGALI', 'info@trustcapitalkira.com', 'Deposit-Taking Microfinance Company'),
('INKUNGA FINANCE PLC', 'RUBENGERA', 'KARONGI', 'WESTERN PROVINCE', 'info@inkungafinance.com', 'Deposit-Taking Microfinance Company'),
('UMURIMO FINANCE PLC', 'KAMEMBE', 'RUSIZI', 'WESTERN PROVINCE', 'umurimofinanceltd@gmail.com', 'Deposit-Taking Microfinance Company'),
('JALI SC PLC', 'KIMISAGARA', 'NYARUGENGE', 'CITY OF KIGALI', 'info@jalisc.rw', 'Deposit-Taking Microfinance Company'),
('BRAC Rwanda Microfinance PLC', 'REMERA', 'GASABO', 'CITY OF KIGALI', 'upoma.an@brac.net', 'Deposit-Taking Microfinance Company'),
('ATLANTIQUE MICROFINANCE PLC', 'NYARUGENGE', 'NYARUGENGE', 'CITY OF KIGALI', 'info@amifa-rw.net', 'Deposit-Taking Microfinance Company'),
('AB Rwanda PLC', 'NYARUGENGE', 'NYARUGENGE', 'CITY OF KIGALI', 'info@abr.rw', 'Deposit-Taking Microfinance Company'),
('URWEGO FINANCE CBC', 'REMERA', 'GASABO', 'CITY OF KIGALI', 'info@urwegobank.com', 'Deposit-Taking Microfinance Company'),
('LOLC UNGUKA FINANCE PLC', 'NYARUGENGE', 'NYARUGENGE', 'CITY OF KIGALI', 'info@lolcunguka.com', 'Deposit-Taking Microfinance Company'),
('COOPERATIVE D''EPARGNE ET DE CREDIT DE RUREMBO', 'RUREMBO', 'NYABIHU', 'WESTERN PROVINCE', 'abisunganyesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO KALISIMBI JENDA', 'JENDA', 'NYABIHU', 'WESTERN PROVINCE', 'saccojenda2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('DUKIZANYE MULINGA SACCO', 'MULINGA', 'NYABIHU', 'WESTERN PROVINCE', 'usaccomulinga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SANGA SACCO', 'SHYIRA', 'NYABIHU', 'WESTERN PROVINCE', 'saccoshyira@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TURAHUMURIJWE SACCO', 'BUGESHI', 'RUBAVU', 'WESTERN PROVINCE', 'turahumurijwesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO INTOZAMUCO', 'BUSASAMANA', 'RUBAVU', 'WESTERN PROVINCE', 'saccointozamuco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO ISANGANIRO', 'CYANZARWE', 'RUBAVU', 'WESTERN PROVINCE', 'saccoisanganiro2022@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO SERUKA', 'GISENYI', 'RUBAVU', 'WESTERN PROVINCE', 'saccoseruka@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('ICYEZA', 'KANAMA', 'RUBAVU', 'WESTERN PROVINCE', 'saccoicyeza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('ABADAHARANA SACCO', 'KANZENZE', 'RUBAVU', 'WESTERN PROVINCE', 'abadaharanasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('IMBONERA SACCO MUDENDE', 'MUDENDE', 'RUBAVU', 'WESTERN PROVINCE', 'imbonerasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('UMUSHYIKIRANO SACCO', 'NYAKILIBA', 'RUBAVU', 'WESTERN PROVINCE', 'umushyikiranosacco2023@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('ISHAKWE SACCO', 'NYAMYUMBA', 'RUBAVU', 'WESTERN PROVINCE', 'saccoishakwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO UMWIMERERE', 'NYUNDO', 'RUBAVU', 'WESTERN PROVINCE', 'umwimereresacco95@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('INKERAGUTABARA SACCO OF RUBAVU', 'RUBAVU', 'RUBAVU', 'WESTERN PROVINCE', 'isaru2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('INTARUTWA SACCO YA RUGERERO', 'RUGERERO', 'RUBAVU', 'WESTERN PROVINCE', 'intarutwasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TERIMBERE SACCO BWIRA', 'BWIRA', 'NGORORERO', 'WESTERN PROVINCE', 'teraimbere@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('UMUSUNGI SACCO GATUMBA', 'GATUMBA', 'NGORORERO', 'WESTERN PROVINCE', 'saccogatumba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('HINDIRO SACCO', 'HINDIRO', 'NGORORERO', 'WESTERN PROVINCE', 'hindirosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO KABAYA JYAMBERE', 'KABAYA', 'NGORORERO', 'WESTERN PROVINCE', 'saccokabaya@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('UMUKORE SACCO', 'KAGEYO', 'NGORORERO', 'WESTERN PROVINCE', 'saccoumukore@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO TUGANE HEZA', 'KAVUMU', 'NGORORERO', 'WESTERN PROVINCE', 'hezasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('MATYAZO SACCO', 'MATYAZO', 'NGORORERO', 'WESTERN PROVINCE', 'matyazosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('HAGURUKA UKORE SACCO-MUHANDA', 'MUHANDA', 'NGORORERO', 'WESTERN PROVINCE', 'muhandasacco04@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('MUHORORO SACCO', 'MUHORORO', 'NGORORERO', 'WESTERN PROVINCE', 'muhororosacco2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('JYAMBERE NDARO SACCO', 'NDARO', 'NGORORERO', 'WESTERN PROVINCE', 'saccojyamberendaro2017@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('MAGIRIRANE SACCO', 'NGORORERO', 'NGORORERO', 'WESTERN PROVINCE', 'magiriranesacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('INYANGE SACCO NSIBO', 'NYANGE', 'NGORORERO', 'WESTERN PROVINCE', 'inyangesacconsibo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('GIRUBUKIRE SACCO SOVU', 'SOVU', 'NGORORERO', 'WESTERN PROVINCE', 'girubukire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO IBAKWE RYA BONEZA', 'BONEZA', 'RUTSIRO', 'WESTERN PROVINCE', 'saccoibakwe875@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO ABESAMIHIGO BA GIHANGO', 'GIHANGO', 'RUTSIRO', 'WESTERN PROVINCE', 'saccoagi20@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO NGWINO UREBE KIGEYO', 'KIGEYO', 'RUTSIRO', 'WESTERN PROVINCE', 'saccokigeyo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO TUZIGAMIRE ABACU KIVUMU', 'KIVUMU', 'RUTSIRO', 'WESTERN PROVINCE', 'saccokivumu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO IMBERE HEZA MANIHIRA', 'MANIHIRA', 'RUTSIRO', 'WESTERN PROVINCE', 'saccoimberehezamanihira@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCOTUGENDANEN IGIHEMUKURA', 'MUKURA', 'RUTSIRO', 'WESTERN PROVINCE', 'saccomukura@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('INDASHYIKIRWA ZA MURUNDA SACCO', 'MURUNDA', 'RUTSIRO', 'WESTERN PROVINCE', 'murundasacco2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('IMBANZAMIHIGO SACCO', 'MUSASA', 'RUTSIRO', 'WESTERN PROVINCE', 'saccomusasa@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO TERIMBERE MUSHONYI', 'MUSHONYI', 'RUTSIRO', 'WESTERN PROVINCE', 'saccoterim2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO DUFITUMURAVA MUSHUBATI', 'MUSHUBATI', 'RUTSIRO', 'WESTERN PROVINCE', 'saccodumu88@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO NYABIRASI_RUTSIRO', 'NYABIRASI', 'RUTSIRO', 'WESTERN PROVINCE', 'sacconyabiru@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO DUKUNGAHARE RUHANGO', 'RUHANGO', 'RUTSIRO', 'WESTERN PROVINCE', 'saccoduru18@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO ICYEREKEZO RUSEBEYA', 'RUSEBEYA', 'RUTSIRO', 'WESTERN PROVINCE', 'saccoruse@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('BWISHYURA SACCO', 'BWISHYURA', 'KARONGI', 'WESTERN PROVINCE', 'bwishyurasacco2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('INDATSIKIRA SACCO GASHALI', 'GASHARI', 'KARONGI', 'WESTERN PROVINCE', 'indatsikirasaccogashali@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('GISHYITA SACCO', 'GISHYITA', 'KARONGI', 'WESTERN PROVINCE', 'gishyitasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO GITESI', 'GITESI', 'KARONGI', 'WESTERN PROVINCE', 'saccogitesi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('DUHASHYUBUKENE SACCO MUBUGA', 'MUBUGA', 'KARONGI', 'WESTERN PROVINCE', 'mubugasacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('IMPARANIRAKURUSHA', 'MURAMBI', 'KARONGI', 'WESTERN PROVINCE', 'murambisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO NGWINO UREBE', 'MURUNDI', 'KARONGI', 'WESTERN PROVINCE', 'saccongwinurebe2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('MUTUNTU SACCO', 'MUTUNTU', 'KARONGI', 'WESTERN PROVINCE', 'mutuntusacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO RUBENGERA', 'RUBENGERA', 'KARONGI', 'WESTERN PROVINCE', 'saccorubengera@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('RUGABANO SACCO', 'RUGABANO', 'KARONGI', 'WESTERN PROVINCE', 'saccorugabano@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO ISONGA RUGANDA', 'RUGANDA', 'KARONGI', 'WESTERN PROVINCE', 'ssaccoisonga@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TWIYUBAKE RWANKUBA', 'RWANKUBA', 'KARONGI', 'WESTERN PROVINCE', 'saccotwiyubakerwankuba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TWUMBA SACCO', 'TWUMBA', 'KARONGI', 'WESTERN PROVINCE', 'twumbasac@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('BUSHENGE SACCO', 'BUSHENGE', 'NYAMASHEKE', 'WESTERN PROVINCE', 'saccobushenge@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TERIMBERE RUHARAMBUGA SACCO', 'RUHARAMBUGA', 'NYAMASHEKE', 'WESTERN PROVINCE', 'sruharambuga2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('BUSHEKERI SACCO', 'BUSHEKERI', 'NYAMASHEKE', 'WESTERN PROVINCE', 'bushekerisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('DUFATANYE KARENGERA SACCO', 'KARENGERA', 'NYAMASHEKE', 'WESTERN PROVINCE', 'saccokarengera21@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('NYABITEKERI SACCO', 'NYABITEKERI', 'NYAMASHEKE', 'WESTERN PROVINCE', 'nyabitekesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SHANGI SACCO', 'SHANGI', 'NYAMASHEKE', 'WESTERN PROVINCE', 'shangi.sacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('CYATO SACCO', 'CYATO', 'NYAMASHEKE', 'WESTERN PROVINCE', 'saccocyato2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('KAGANO SACCO', 'KAGANO', 'NYAMASHEKE', 'WESTERN PROVINCE', 'kaganosaccony@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('UNGUKA GIHOMBO SACCO', 'GIHOMBO', 'NYAMASHEKE', 'WESTERN PROVINCE', 'saccogihombo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('AMIZERO MACUBA SACCO', 'MACUBA', 'NYAMASHEKE', 'WESTERN PROVINCE', 'amizerosacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO WISIGARA RANGIRO', 'RANGIRO', 'NYAMASHEKE', 'WESTERN PROVINCE', 'wisigararangirosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TWISUNGANE MAHEMBE SACCO', 'MAHEMBE', 'NYAMASHEKE', 'WESTERN PROVINCE', 'mahembesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TWITEZIMBERE KILIMBI SACCO', 'KIRIMBI', 'NYAMASHEKE', 'WESTERN PROVINCE', 'tkirimbisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('KANJONGO SACCO', 'KANJONGO', 'NYAMASHEKE', 'WESTERN PROVINCE', 'saccokanjongo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('KARAMBI VISION SACCO', 'KARAMBI', 'NYAMASHEKE', 'WESTERN PROVINCE', 'karambivisionsacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('IMBATURABUKUNGU SACCO', 'BUTARE', 'RUSIZI', 'WESTERN PROVINCE', '11imbaturabukungu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TUBEHO SACCO BWEYEYE', 'BWEYEYE', 'RUSIZI', 'WESTERN PROVINCE', 'tubehosaccobweyeye1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('URUYANGE SACCO', 'BUGARAMA', 'RUSIZI', 'WESTERN PROVINCE', 'uruyangesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('TUBEKWISONGA SACCO', 'GASHONGA', 'RUSIZI', 'WESTERN PROVINCE', 'tubekwisongasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('IREMBO SACCO', 'GIHEKE', 'RUSIZI', 'WESTERN PROVINCE', 'irembosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('UMUSINGI SACCO GIHUNDWE', 'GIHUNDWE', 'RUSIZI', 'WESTERN PROVINCE', 'umusingisaccogihundwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('UBUMWE SACCO', 'GIKUNDAMVURA', 'RUSIZI', 'WESTERN PROVINCE', 'saccoubumwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('INDATWA GITAMBI SACCO', 'GITAMBI', 'RUSIZI', 'WESTERN PROVINCE', 'saccogitambi@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('NKAMIRA SACCO', 'KAMEMBE', 'RUSIZI', 'WESTERN PROVINCE', 'nkamirasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('MASHYUZA SACCO', 'MUGANZA', 'RUSIZI', 'WESTERN PROVINCE', 'sacco.mashyuza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('HUZA SACCO', 'MURURU', 'RUSIZI', 'WESTERN PROVINCE', 'saccomururu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO REBIMBERE NKANKA', 'NKANKA', 'RUSIZI', 'WESTERN PROVINCE', 'rebimberesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('NGIRANKUGIRE SACCO', 'NKOMBO', 'RUSIZI', 'WESTERN PROVINCE', 'sacconkombo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO NTUKABUMWE NKUNGU', 'NKUNGU', 'RUSIZI', 'WESTERN PROVINCE', 'nkungusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('NTUSIGARE SACCO', 'NYAKABUYE', 'RUSIZI', 'WESTERN PROVINCE', 'ntusigaresacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('SACCO ABESAMIHIGO NYAKARENZO', 'NYAKARENZO', 'RUSIZI', 'WESTERN PROVINCE', 'saccoabesamihigo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('NZAHAHA INTSINZI SACCO', 'NZAHAHA', 'RUSIZI', 'WESTERN PROVINCE', 'intsinzisaccon@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
('BAHO SACCO', 'RWIMBOGO', 'RUSIZI', 'WESTERN PROVINCE', 'bahosaccorwimbogo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)')
ON CONFLICT DO NOTHING;