-- Backfill missing Umurenge SACCOs so seed data matches the reference dataset.
with missing(name, district, sector_code, province, email, category, sector) as (
  values
    ('COOPERATIVE D''EPARGNE ET DE CREDIT DE RUREMBO', 'NYABIHU', 'NYABIHU-RUREMBO', 'WESTERN PROVINCE', 'abisunganyesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUREMBO'),
    ('SACCO KALISIMBI JENDA', 'NYABIHU', 'NYABIHU-JENDA', 'WESTERN PROVINCE', 'saccojenda2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'JENDA'),
    ('DUKIZANYE MULINGA SACCO', 'NYABIHU', 'NYABIHU-MULINGA', 'WESTERN PROVINCE', 'usaccomulinga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MULINGA'),
    ('SANGA SACCO', 'NYABIHU', 'NYABIHU-SHYIRA', 'WESTERN PROVINCE', 'saccoshyira@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'SHYIRA'),
    ('TURAHUMURIJWE SACCO', 'RUBAVU', 'RUBAVU-BUGESHI', 'WESTERN PROVINCE', 'turahumurijwesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BUGESHI'),
    ('SACCO INTOZAMUCO', 'RUBAVU', 'RUBAVU-BUSASAMANA', 'WESTERN PROVINCE', 'saccointozamuco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BUSASAMANA'),
    ('SACCO ISANGANIRO', 'RUBAVU', 'RUBAVU-CYANZARWE', 'WESTERN PROVINCE', 'saccoisanganiro2022@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'CYANZARWE'),
    ('SACCO SERUKA', 'RUBAVU', 'RUBAVU-GISENYI', 'WESTERN PROVINCE', 'saccoseruka@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GISENYI'),
    ('ICYEZA', 'RUBAVU', 'RUBAVU-KANAMA', 'WESTERN PROVINCE', 'saccoicyeza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KANAMA'),
    ('ABADAHARANA SACCO', 'RUBAVU', 'RUBAVU-KANZENZE', 'WESTERN PROVINCE', 'abadaharanasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KANZENZE'),
    ('IMBONERA SACCO MUDENDE', 'RUBAVU', 'RUBAVU-MUDENDE', 'WESTERN PROVINCE', 'imbonerasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MUDENDE'),
    ('UMUSHYIKIRANO SACCO', 'RUBAVU', 'RUBAVU-NYAKILIBA', 'WESTERN PROVINCE', 'umushyikiranosacco2023@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NYAKILIBA'),
    ('ISHAKWE SACCO', 'RUBAVU', 'RUBAVU-NYAMYUMBA', 'WESTERN PROVINCE', 'saccoishakwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NYAMYUMBA'),
    ('SACCO UMWIMERERE', 'RUBAVU', 'RUBAVU-NYUNDO', 'WESTERN PROVINCE', 'umwimereresacco95@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NYUNDO'),
    ('INKERAGUTABARA SACCO OF RUBAVU', 'RUBAVU', 'RUBAVU-RUBAVU', 'WESTERN PROVINCE', 'isaru2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUBAVU'),
    ('INTARUTWA SACCO YA RUGERERO', 'RUBAVU', 'RUBAVU-RUGERERO', 'WESTERN PROVINCE', 'intarutwasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUGERERO'),
    ('TERIMBERE SACCO BWIRA', 'NGORORERO', 'NGORORERO-BWIRA', 'WESTERN PROVINCE', 'teraimbere@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BWIRA'),
    ('UMUSUNGI SACCO GATUMBA', 'NGORORERO', 'NGORORERO-GATUMBA', 'WESTERN PROVINCE', 'saccogatumba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GATUMBA'),
    ('HINDIRO SACCO', 'NGORORERO', 'NGORORERO-HINDIRO', 'WESTERN PROVINCE', 'hindirosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'HINDIRO'),
    ('SACCO KABAYA JYAMBERE', 'NGORORERO', 'NGORORERO-KABAYA', 'WESTERN PROVINCE', 'saccokabaya@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KABAYA'),
    ('UMUKORE SACCO', 'NGORORERO', 'NGORORERO-KAGEYO', 'WESTERN PROVINCE', 'saccoumukore@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KAGEYO'),
    ('SACCO TUGANE HEZA', 'NGORORERO', 'NGORORERO-KAVUMU', 'WESTERN PROVINCE', 'hezasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KAVUMU'),
    ('MATYAZO SACCO', 'NGORORERO', 'NGORORERO-MATYAZO', 'WESTERN PROVINCE', 'matyazosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MATYAZO'),
    ('HAGURUKA UKORE SACCO-MUHANDA', 'NGORORERO', 'NGORORERO-MUHANDA', 'WESTERN PROVINCE', 'muhandasacco04@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MUHANDA'),
    ('MUHORORO SACCO', 'NGORORERO', 'NGORORERO-MUHORORO', 'WESTERN PROVINCE', 'muhororosacco2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MUHORORO'),
    ('JYAMBERE NDARO SACCO', 'NGORORERO', 'NGORORERO-NDARO', 'WESTERN PROVINCE', 'saccojyamberendaro2017@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NDARO'),
    ('MAGIRIRANE SACCO', 'NGORORERO', 'NGORORERO-NGORORERO', 'WESTERN PROVINCE', 'magiriranesacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NGORORERO'),
    ('INYANGE SACCO NSIBO', 'NGORORERO', 'NGORORERO-NYANGE', 'WESTERN PROVINCE', 'inyangesacconsibo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NYANGE'),
    ('GIRUBUKIRE SACCO SOVU', 'NGORORERO', 'NGORORERO-SOVU', 'WESTERN PROVINCE', 'girubukire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'SOVU'),
    ('SACCO TWIYUBAKE RWANKUBA', 'KARONGI', 'KARONGI-RWANKUBA', 'WESTERN PROVINCE', 'twiyubakerwankuba2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RWANKUBA'),
    ('SACCO NGWINO UREBE', 'KARONGI', 'KARONGI-BWISHYURA', 'WESTERN PROVINCE', 'saccongwino2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BWISHYURA'),
    ('TWUMBA SACCO', 'KARONGI', 'KARONGI-TWUMBA', 'WESTERN PROVINCE', 'twumbasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'TWUMBA'),
    ('SACCO GITESI', 'KARONGI', 'KARONGI-GITESI', 'WESTERN PROVINCE', 'saccogitesi2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GITESI'),
    ('DUHASHYUBUKENE SACCO MUBUGA', 'KARONGI', 'KARONGI-MUBUGA', 'WESTERN PROVINCE', 'mubugasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MUBUGA'),
    ('MUTUNTU SACCO', 'KARONGI', 'KARONGI-MUTUNTU', 'WESTERN PROVINCE', 'mutuntusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MUTUNTU'),
    ('SACCO ICYEZA GASHALI', 'KARONGI', 'KARONGI-GASHALI', 'WESTERN PROVINCE', 'saccoicyezagashali@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GASHALI'),
    ('SACCO ISONGA RUGANDA', 'KARONGI', 'KARONGI-RUGANDA', 'WESTERN PROVINCE', 'isongaruganda@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUGANDA'),
    ('TWIYUBAKE RWANKUBA', 'KARONGI', 'KARONGI-RWANKUBA', 'WESTERN PROVINCE', 'twiyubakerwankuba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RWANKUBA'),
    ('SACCO MAGIRIRANE', 'KARONGI', 'KARONGI-KAYENZI', 'WESTERN PROVINCE', 'saccomagirirane@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KAYENZI'),
    ('SACCO NGWINO UREBE KIGEYO', 'RUTSIRO', 'RUTSIRO-KIGEYO', 'WESTERN PROVINCE', 'sacco.ngwinourebekigeyo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KIGEYO'),
    ('SACCO ABESAMIHIGO BA GIHANGO', 'RUTSIRO', 'RUTSIRO-GIHANGO', 'WESTERN PROVINCE', 'saccogihango@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GIHANGO'),
    ('SACCO DUKUNGAHARE RUHANGO', 'RUTSIRO', 'RUTSIRO-RUHANGO', 'WESTERN PROVINCE', 'saccoruahango@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUHANGO'),
    ('SACCO IMBERE HEZA MANIHIRA', 'RUTSIRO', 'RUTSIRO-MANIHIRA', 'WESTERN PROVINCE', 'manihirasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MANIHIRA'),
    ('INDASHYIKIRWA ZA MURUNDA SACCO', 'RUTSIRO', 'RUTSIRO-MURUNDA', 'WESTERN PROVINCE', 'indashikirwasaccomurunda@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MURUNDA'),
    ('SACCO NGWINO UREBE RUSEKE', 'RUTSIRO', 'RUTSIRO-RUSEKE', 'WESTERN PROVINCE', 'saccoruseke@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUSEKE'),
    ('SACCO KUNGAHARE RUSESE', 'RUTSIRO', 'RUTSIRO-RUSESE', 'WESTERN PROVINCE', 'saccoruseserutsiro@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUSESE'),
    ('SACCO KALISIMBI NYABIRASI', 'RUTSIRO', 'RUTSIRO-NYABIRASI', 'WESTERN PROVINCE', 'sacconyabirasi232@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NYABIRASI'),
    ('SACCO KALISIMBI NKWANIRA', 'RUTSIRO', 'RUTSIRO-NKWANIRA', 'WESTERN PROVINCE', 'sacconkwanira2016@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NKWANIRA'),
    ('SACCO TUZIGAMIRE ABACU KIVUMU', 'RUTSIRO', 'RUTSIRO-KIVUMU', 'WESTERN PROVINCE', 'saccokivumu2017@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KIVUMU'),
    ('SACCO TUZAMUKANE RUGOMA', 'RUTSIRO', 'RUTSIRO-RUGOMA', 'WESTERN PROVINCE', 'saccorugoma2015@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUGOMA'),
    ('SACCO TERIMBERE MUSHONYI', 'RUTSIRO', 'RUTSIRO-MUSHONYI', 'WESTERN PROVINCE', 'saccomushonyi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MUSHONYI'),
    ('SACCO REBIMBERE NKANKA', 'RUSIZI', 'RUSIZI-NKANKA', 'WESTERN PROVINCE', 'nkankasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NKANKA'),
    ('SACCO TWIYUBAKE NYAKARENZO', 'RUSIZI', 'RUSIZI-NYAKARENZO', 'WESTERN PROVINCE', 'sacconyakarenzo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NYAKARENZO'),
    ('UMUSINGI SACCO GIHUNDWE', 'RUSIZI', 'RUSIZI-GIHUNDWE', 'WESTERN PROVINCE', 'umusinggi2019@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GIHUNDWE'),
    ('NGIRANKUGIRE SACCO', 'RUSIZI', 'RUSIZI-GIKUNDAMVURA', 'WESTERN PROVINCE', 'ngirankugire2019@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GIKUNDAMVURA'),
    ('HUZA SACCO', 'RUSIZI', 'RUSIZI-GIHEKE', 'WESTERN PROVINCE', 'huzasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'GIHEKE'),
    ('INTSINZI SACCO BUGARIKA', 'RUSIZI', 'RUSIZI-BUGARIKA', 'WESTERN PROVINCE', 'saccobugarika@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BUGARIKA'),
    ('SACCO UBUMWE KAGANO', 'NYAMASHEKE', 'NYAMASHEKE-KAGANO', 'WESTERN PROVINCE', 'saccoubagano@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KAGANO'),
    ('SACCO KU NTEKO CYATO', 'NYAMASHEKE', 'NYAMASHEKE-CYATO', 'WESTERN PROVINCE', 'cyatosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'CYATO'),
    ('SACCO AMIZERO BUSHEKERI', 'NYAMASHEKE', 'NYAMASHEKE-BUSHEKERI', 'WESTERN PROVINCE', 'amizero@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BUSHEKERI'),
    ('SACCO BUSHENGE', 'NYAMASHEKE', 'NYAMASHEKE-BUSHENGE', 'WESTERN PROVINCE', 'saccobushenge@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BUSHENGE'),
    ('SACCO BWOBAKIRA', 'NYAMASHEKE', 'NYAMASHEKE-BWOBAKIRA', 'WESTERN PROVINCE', 'bwobakirasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BWOBAKIRA'),
    ('SACCO DUFATANYE KARENGERA', 'NYAMASHEKE', 'NYAMASHEKE-KARENGERA', 'WESTERN PROVINCE', 'dufatanye2017@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KARENGERA'),
    ('SACCO IBAKWE RYA BONEZA', 'NYAMASHEKE', 'NYAMASHEKE-BONEZA', 'WESTERN PROVINCE', 'ibakwerwiboneza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BONEZA'),
    ('SACCO IMBARUTSO SHANGI', 'NYAMASHEKE', 'NYAMASHEKE-SHANGI', 'WESTERN PROVINCE', 'shangisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'SHANGI'),
    ('SACCO WISIGARA RANGIRO', 'NYAMASHEKE', 'NYAMASHEKE-RANGIRO', 'WESTERN PROVINCE', 'wisigara@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RANGIRO'),
    ('SACCO TERIMBERE RUHARAMBUGA', 'NYAMASHEKE', 'NYAMASHEKE-RUHARAMBUGA', 'WESTERN PROVINCE', 'terimbere@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUHARAMBUGA'),
    ('SACCO KARAMBO VISION', 'NYAMASHEKE', 'NYAMASHEKE-KARAMBO', 'WESTERN PROVINCE', 'saccokarambo2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KARAMBO'),
    ('SACCO BAHO', 'RUSIZI', 'RUSIZI-KAMEMBE', 'WESTERN PROVINCE', 'bahosacco2009@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KAMEMBE'),
    ('SACCO UBUMWE', 'RUSIZI', 'RUSIZI-BUGARAMA', 'WESTERN PROVINCE', 'ubumwesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'BUGARAMA'),
    ('SACCO NKARA', 'RUSIZI', 'RUSIZI-NKARA', 'WESTERN PROVINCE', 'sacconkara2016@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NKARA'),
    ('SACCO NTUSIGARE MUGANZA', 'RUSIZI', 'RUSIZI-MUGANZA', 'WESTERN PROVINCE', 'ntusigaremuganza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MUGANZA'),
    ('SACCO TWISUNGANE MAHEMBE', 'NYAMASHEKE', 'NYAMASHEKE-MAHEMBE', 'WESTERN PROVINCE', 'twisunganemahembe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MAHEMBE'),
    ('SACCO NZAHAHA INTSINZI', 'RUSIZI', 'RUSIZI-NZAHAHA', 'WESTERN PROVINCE', 'nzahahaintsinizisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'NZAHAHA'),
    ('SACCO UMWUGA', 'RUSIZI', 'RUSIZI-MURURU', 'WESTERN PROVINCE', 'umwugasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'MURURU'),
    ('SACCO UMURAVA RF AT', 'RUTSIRO', 'RUTSIRO-RUBAVU', 'WESTERN PROVINCE', 'umuravasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'RUBAVU'),
    ('SACCO INKINGI Y''ITERAMBERE KIVU', 'NYARUGURU', 'NYARUGURU-KIVU', 'SOUTHERN PROVINCE', 'twizigereiteramberekivu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'KIVU')
  )
  insert into app.saccos (
  name,
  district,
  sector_code,
  province,
  email,
  category,
  sector,
  merchant_code,
  status,
  metadata
)
select
  m.name,
  m.district,
  m.sector_code,
  m.province,
  m.email,
  coalesce(m.category, 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)'),
  m.sector,
  null,
  'ACTIVE',
  '{}'::jsonb
from missing m
where not exists (
  select 1
  from app.saccos s
  where s.name = m.name
    and s.district = m.district
);
