name: Build Staff Android APK

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/admin/**'
      - '.github/workflows/build-android-staff-apk.yml'
  workflow_dispatch:
    inputs:
      server_url:
        description: 'Server URL for the APK to connect to'
        required: false
        default: 'https://staff.ibimina.rw'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm run build --filter @ibimina/config --filter @ibimina/ui
      
      - name: Configure Capacitor server URL
        if: github.event.inputs.server_url != ''
        env:
          SERVER_URL: ${{ github.event.inputs.server_url }}
        run: |
          cd apps/admin
          sed -i "s|https://.*kirk.replit.dev|$SERVER_URL|g" capacitor.config.ts
      
      - name: Sync Capacitor
        run: |
          cd apps/admin
          npx cap sync android
      
      - name: Build Android Debug APK
        run: |
          cd apps/admin/android
          chmod +x gradlew
          ./gradlew assembleDebug
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ibimina-staff-debug-apk
          path: apps/admin/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
      
      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: apps/admin/android/app/build/outputs/apk/debug/app-debug.apk
          name: Staff App ${{ github.ref_name }}
          body: |
            ## Ibimina Staff Mobile App
            
            **Version**: ${{ github.ref_name }}
            **Platform**: Android (Debug Build)
            **Server**: ${{ github.event.inputs.server_url || 'Default' }}
            
            ### Installation
            1. Download the APK file
            2. Enable "Install from Unknown Sources" on your Android device
            3. Install the APK
            
            ### What's New
            See commits for details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm run build --filter @ibimina/config --filter @ibimina/ui
      
      - name: Sync Capacitor
        run: |
          cd apps/admin
          npx cap sync android
      
      - name: Build Android Release APK
        run: |
          cd apps/admin/android
          chmod +x gradlew
          ./gradlew assembleRelease
      
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: apps/admin/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ibimina-staff-release-apk
          path: apps/admin/android/app/build/outputs/apk/release/app-release-signed.apk
          retention-days: 90
