name: mobile-ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "apps/client/**"
      - "packages/core/**"
      - "packages/config/**"
      - ".github/workflows/mobile.yml"

jobs:
  detox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Detox suites
        run: pnpm --filter @ibimina/client run test:detox

      - name: Upload Detox artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detox-report
          path: apps/client/tests/detox

  telemetry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck telemetry modules
        run: pnpm --filter @ibimina/core run typecheck
