name: Supabase Functions Deploy
on:
  push:
    paths:
      - "supabase/functions/**"
      - "supabase/migrations/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      - run: supabase db push
      - run: supabase functions deploy sms-inbox sms-ai-parse payments-apply recon-exceptions reports-export admin-reset-mfa
    permissions:
      contents: read
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
